/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management.system.user;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import school.management.system.admin.dbConfig;
import javax.swing.JOptionPane;

/**
 *
 * @author Beamtech
 */
public class log extends javax.swing.JFrame {
 String daytime_night,Hour,second,Minute,username,pass;
    /**
     * Creates new form log
     *
     */
  dbConfig db= new dbConfig();
    public log() {
        initComponents();
        dateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        loginLogo = new javax.swing.JLabel();
        usernameJlbel = new javax.swing.JLabel();
        passwordJlabel = new javax.swing.JLabel();
        usernameJtxt = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        loginCmd = new javax.swing.JButton();
        headerPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tHourLbel = new javax.swing.JLabel();
        blink1 = new javax.swing.JLabel();
        tMinsLbel = new javax.swing.JLabel();
        blink2 = new javax.swing.JLabel();
        tSecLbel = new javax.swing.JLabel();
        Pm_AmJlb = new javax.swing.JLabel();
        dayOfWeeks = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        minimizeCmd = new javax.swing.JButton();
        CloseCmd = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        imgHolder = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(150, 50, 959, 683));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(773, 403));
        setName("JFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(983, 683));
        getContentPane().setLayout(null);

        mainPane.setMinimumSize(new java.awt.Dimension(959, 683));
        mainPane.setLayout(null);

        loginPane.setBackground(new java.awt.Color(0, 51, 51));
        loginPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 204, 255), new java.awt.Color(153, 255, 255))));
        loginPane.setMinimumSize(new java.awt.Dimension(56, 350));
        loginPane.setOpaque(false);
        loginPane.setLayout(null);

        loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/select-user.png"))); // NOI18N
        loginPane.add(loginLogo);
        loginLogo.setBounds(90, 6, 80, 93);

        usernameJlbel.setBackground(new java.awt.Color(51, 51, 51));
        usernameJlbel.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        usernameJlbel.setForeground(new java.awt.Color(0, 204, 204));
        usernameJlbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameJlbel.setText("Username");
        usernameJlbel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/LOGO.png")))); // NOI18N
        usernameJlbel.setOpaque(true);
        loginPane.add(usernameJlbel);
        usernameJlbel.setBounds(39, 99, 180, 30);

        passwordJlabel.setBackground(new java.awt.Color(51, 51, 51));
        passwordJlabel.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        passwordJlabel.setForeground(new java.awt.Color(0, 204, 204));
        passwordJlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordJlabel.setText("password");
        passwordJlabel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/LOGO.png")))); // NOI18N
        passwordJlabel.setOpaque(true);
        loginPane.add(passwordJlabel);
        passwordJlabel.setBounds(39, 193, 180, 30);

        usernameJtxt.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        loginPane.add(usernameJtxt);
        usernameJtxt.setBounds(39, 135, 180, 27);

        jPassword.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        loginPane.add(jPassword);
        jPassword.setBounds(39, 234, 180, 27);

        loginCmd.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        loginCmd.setForeground(new java.awt.Color(0, 204, 255));
        loginCmd.setText("Log In");
        loginCmd.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        loginCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCmdActionPerformed(evt);
            }
        });
        loginPane.add(loginCmd);
        loginCmd.setBounds(89, 309, 85, 28);

        mainPane.add(loginPane);
        loginPane.setBounds(528, 53, 246, 350);

        headerPane.setBackground(new java.awt.Color(0, 0, 0));
        headerPane.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/LOGO1.png"))); // NOI18N
        jLabel1.setText(" ");
        headerPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 60, 50);

        tHourLbel.setFont(new java.awt.Font("Digital-7", 1, 24)); // NOI18N
        tHourLbel.setForeground(new java.awt.Color(0, 204, 255));
        tHourLbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tHourLbel.setText("00");
        headerPane.add(tHourLbel);
        tHourLbel.setBounds(540, 0, 30, 40);

        blink1.setFont(new java.awt.Font("Digital-7", 1, 18)); // NOI18N
        blink1.setForeground(new java.awt.Color(0, 204, 255));
        blink1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blink1.setText(":");
        headerPane.add(blink1);
        blink1.setBounds(570, 0, 10, 40);

        tMinsLbel.setFont(new java.awt.Font("Digital-7", 1, 24)); // NOI18N
        tMinsLbel.setForeground(new java.awt.Color(0, 204, 255));
        tMinsLbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tMinsLbel.setText("00");
        headerPane.add(tMinsLbel);
        tMinsLbel.setBounds(580, 0, 40, 40);

        blink2.setFont(new java.awt.Font("Digital-7", 1, 18)); // NOI18N
        blink2.setForeground(new java.awt.Color(0, 204, 255));
        blink2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blink2.setText(":");
        headerPane.add(blink2);
        blink2.setBounds(620, 0, 10, 40);

        tSecLbel.setFont(new java.awt.Font("Digital-7", 1, 24)); // NOI18N
        tSecLbel.setForeground(new java.awt.Color(0, 204, 255));
        tSecLbel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tSecLbel.setText("00");
        headerPane.add(tSecLbel);
        tSecLbel.setBounds(640, 0, 30, 40);

        Pm_AmJlb.setFont(new java.awt.Font("Digital-7", 1, 24)); // NOI18N
        Pm_AmJlb.setForeground(new java.awt.Color(0, 204, 255));
        Pm_AmJlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pm_AmJlb.setText("PM");
        headerPane.add(Pm_AmJlb);
        Pm_AmJlb.setBounds(670, 0, 30, 40);

        dayOfWeeks.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        dayOfWeeks.setForeground(new java.awt.Color(255, 255, 255));
        dayOfWeeks.setText("dayOfWeek");
        headerPane.add(dayOfWeeks);
        dayOfWeeks.setBounds(338, 11, 111, 34);

        jLabel9.setText("Anim gif");
        headerPane.add(jLabel9);
        jLabel9.setBounds(66, 0, 52, 67);

        minimizeCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/mimimize2.png"))); // NOI18N
        minimizeCmd.setIconTextGap(0);
        minimizeCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeCmdActionPerformed(evt);
            }
        });
        headerPane.add(minimizeCmd);
        minimizeCmd.setBounds(729, 0, 20, 17);

        CloseCmd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/close1.png"))); // NOI18N
        CloseCmd.setIconTextGap(0);
        CloseCmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCmdActionPerformed(evt);
            }
        });
        headerPane.add(CloseCmd);
        CloseCmd.setBounds(755, 0, 18, 17);

        dateLabel.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date");
        headerPane.add(dateLabel);
        dateLabel.setBounds(210, 11, 122, 34);

        mainPane.add(headerPane);
        headerPane.setBounds(0, 0, 773, 53);

        imgHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgHolder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school/management/system/user/resources/pexels-photo-984539.jpeg"))); // NOI18N
        imgHolder.setIconTextGap(0);
        mainPane.add(imgHolder);
        imgHolder.setBounds(0, 53, 528, 350);

        getContentPane().add(mainPane);
        mainPane.setBounds(0, 0, 959, 683);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCmdActionPerformed
      System.exit(0);
    }//GEN-LAST:event_CloseCmdActionPerformed

    private void minimizeCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeCmdActionPerformed
      setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeCmdActionPerformed

    private void loginCmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCmdActionPerformed
//      usernameJtxt 
//      jPassword
        
        username=usernameJtxt.getText().trim();
        pass=jPassword.getText().trim();
        JOptionPane.showMessageDialog(null, username);
        JOptionPane.showMessageDialog(null, pass);
        // sending data to the database.
        int slash= username.indexOf("/");
         JOptionPane.showMessageDialog(null,slash);
         JOptionPane.showMessageDialog(null,username.substring(0,slash));
        if(username.substring(0,slash).contains("CI")){
            
         login("student");
          JOptionPane.showMessageDialog(null, "login Successful");
                 }else
        {
                 JOptionPane.showMessageDialog(null, "login unSuccessful");
                }
                
    }//GEN-LAST:event_loginCmdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log().setVisible(true);
            }
        });
    }
    // method to display time and date
    
    public void dateTime(){
         
         new Thread(){
          @Override
          public void run(){
              int timeRun=0;
              while(timeRun==0)
              {
                  Calendar cal = new GregorianCalendar();
                  
                  int hour = cal.get(Calendar.HOUR);
                  int minute = cal.get(Calendar.MINUTE);
                  int sec = cal.get(Calendar.SECOND);
                  int AM_PM = cal.get(Calendar.AM_PM);
                 int month = cal.get(Calendar.MONTH);
                 int day = cal.get(Calendar.DAY_OF_MONTH);
                 int year = cal.get(Calendar.YEAR);
                 int dayOfWeek= cal.get(Calendar.DAY_OF_WEEK);
                  if(AM_PM==1){
                     daytime_night ="PM"; 
                  } else {
                      daytime_night = "AM";
                  }
                  if(sec%2==0){
                     blink1.setText(":");
                     blink2.setText(":");
                     dayOfWeeks.setForeground(Color.cyan);
                  }else{
                    blink1.setText("");  
                    blink2.setText("");
                     dayOfWeeks.setForeground(Color.blue);
                  }
                  
                 if(dayOfWeek== 1){
                     dayOfWeeks.setText("Sunday");
                }else if(dayOfWeek== 2){
                     dayOfWeeks.setText("Monday");
                }else if(dayOfWeek== 3){
                     dayOfWeeks.setText("Tuesday");
                }else if(dayOfWeek== 4){
                     dayOfWeeks.setText("Wensday");
                }else if(dayOfWeek== 5){
                     dayOfWeeks.setText("Thursday");
                }else if(dayOfWeek== 6){
                     dayOfWeeks.setText("Friday");
                } else if(dayOfWeek== 7){
                  dayOfWeeks.setText("Sarturday");   
                }  
                
//                Hour =( ( hour < 10 ) ? "0"+hour : hour ) + ""; 
                Hour =((hour==0)&&(AM_PM==1)? 12 : ( ( hour < 10 ) ? "0"+hour : hour ))+""; 
                
                Minute = ( ( minute < 10 ) ? "0"+ minute : minute )  + " ";
                second = ( ( sec < 10 ) ? "0"+ sec : sec )  + "";   
               tHourLbel.setText(Hour);
               tMinsLbel.setText(Minute);
               tSecLbel.setText(second);
               Pm_AmJlb.setText(daytime_night);
               dateLabel.setText((day)+" / "+(month+1)+" / "+year+" ");
              }
          }  
        }.start();
    
    }
    public void login(String table){
        JOptionPane.showMessageDialog(null,table);
         try {   
     String sql = "SELECT * FROM "+table.trim()+" WHERE Username=? and password=? ";
        
         PreparedStatement pst= db.con.prepareStatement(sql);
         pst.setString(1,username);
         pst.setString(2,pass);
         pst.execute();
     } catch (SQLException ex) {
         JOptionPane.showMessageDialog(null,ex);
     }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseCmd;
    private javax.swing.JLabel Pm_AmJlb;
    private javax.swing.JLabel blink1;
    private javax.swing.JLabel blink2;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dayOfWeeks;
    private javax.swing.JPanel headerPane;
    private javax.swing.JLabel imgHolder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton loginCmd;
    private javax.swing.JLabel loginLogo;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel mainPane;
    private javax.swing.JButton minimizeCmd;
    private javax.swing.JLabel passwordJlabel;
    private javax.swing.JLabel tHourLbel;
    private javax.swing.JLabel tMinsLbel;
    private javax.swing.JLabel tSecLbel;
    private javax.swing.JLabel usernameJlbel;
    private javax.swing.JTextField usernameJtxt;
    // End of variables declaration//GEN-END:variables
}
